### ISSUE TITLE
Problem With Point 2

### ISSUE THREAD

**Issue by IDX1997** [chiragk156/cowin#1]
How to do it ?
2. python <path_to_cowin.py> <path_to_json_file>

**Comment by chiragk156** [comment]
First of all, you have to install Python.
Then, open "cmd" and enter "python <path_to_cowin.py> <path_to_json_file>".
where, <path_to_cowin.py> is like Desktop\cowin.py
    and <path_to_json_file> is like Desktop\vaccine_detail.json
